accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),

	# register 
	# url(r'^register/$', views.register, name='register'),
	# test
	# url(r'^users/$', views.users, name='users'),
	# test ex: /2/
	# url(r'^(?P<user_id>\w+)/$', views.user, name='user')
)

coffeeddie/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
 
urlpatterns = patterns('',

    #common
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin', include(admin.site.urls)),
    
    url(r'^login/$', ('accounts.views.log_in'), name='log_in'),
    url(r'^login$', ('accounts.views.log_in'), name='log_in'),

    url(r'^logout/$', ('accounts.views.log_out'), name='log_out'),
    url(r'^logout$', ('accounts.views.log_out'), name='log_out'),

    #main
    url(r'^$', ('project.views.cashbox'), name='cashbox'),

    url(r'^list/$', ('project.views.list'), name='list'),
    url(r'^list$', ('project.views.list'), name='list'),

    url(r'^component/add/$', 'project.views.component_add', name='component_add'),
    url(r'^component/add$', 'project.views.component_add', name='component_add'),
    url(r'^component/(?P<pk>\d+)/edit/$', ('project.views.component_edit'), name='component_edit'),
    url(r'^component/(?P<pk>\d+)/edit$', ('project.views.component_edit'), name='component_edit'),
    
    url(r'^product/add/$', 'project.views.product_add', name='product_add'),
    url(r'^product/add$', 'project.views.product_add', name='product_add'),
    url(r'^product/(?P<pk>\d+)/edit/$', ('project.views.product_edit'), name='product_edit'),
    url(r'^product/(?P<pk>\d+)/edit$', ('project.views.product_edit'), name='product_edit'),
    
    url(r'^order/$', ('project.views.make_order_ajax'), name='order'),
    url(r'^order$', ('project.views.make_order_ajax'), name='order'),
    url(r'^order/(?P<pk>\d+)/$', ('project.views.order_details'), name='order_details'),

    url(r'^employees/$', ('project.views.employee_list'), name='employee_list'),
    url(r'^employees$', ('project.views.employee_list'), name='employee_list'),

    url(r'^employees/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)$', ('project.views.employee_list_specific'), name='employee_list_specific'),
    url(r'^employees/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', ('project.views.employee_list_specific'), name='employee_list_specific'),

    url(r'^stocks/$', ('project.views.stock_list'), name='stock_list'),
    url(r'^stocks$', ('project.views.stock_list'), name='stock_list'),
    url(r'^stocks/add/$', ('project.views.stock_add'), name='stock_add'),
    url(r'^stocks/add$', ('project.views.stock_add'), name='stock_add'),
    url(r'^stocks/(?P<pk>\d+)/edit/$', ('project.views.stock_edit'), name='stock_edit'),
    url(r'^stocks/(?P<pk>\d+)/edit$', ('project.views.stock_edit'), name='stock_edit'),

    url(r'^reports/$', ('project.views.reports'), name='reports'),
    url(r'^reports$', ('project.views.reports'), name='reports'),

    url(r'^about/$', ('project.views.about'), name='about'),
    url(r'^about$', ('project.views.about'), name='about'),
)

project/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models
from accounts.models import User
import datetime

# Create your models here.

class Component(models.Model):
	COMP_CHOICES = (
		(u'ВЫПЕЧКА',u'Выпечка'),
		(u'НАПИТКИ',u'Напитки'),
		(u'СПЕЦИИ',u'Приправы и специи'),
		(u'РАСХОДНИК',u'Расходные материалы'),
	)
	component_title = models.CharField(u'Наименование', max_length=50)
	component_count = models.IntegerField(max_length=10)
	component_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
	component_type = models.CharField(max_length=20, choices=COMP_CHOICES, default='РАСХОДНИК')
	date_add = models.DateField(u'Дата добавления', auto_now=True)

	class Meta:
		verbose_name_plural="Компоненты"
		verbose_name='Компонент'

	def __unicode__(self):
	    return u'%s' % (self.component_title)

class Product(models.Model):
	PRODUCT_CHOICES = (
		(u'ВЫПЕЧКА',u'Выпечка'),
		(u'НАПИТКИ',u'Напитки'),
		(u'СПЕЦИИ',u'Приправы и специи'),
		(u'РАСХОДНИК',u'Расходные материалы'),
	)
	product_title = models.CharField(u'Наименование', max_length=50)
	# product_count = models.IntegerField(max_length=10)
	product_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
	product_type = models.CharField(max_length=20, choices=PRODUCT_CHOICES, default='РАСХОДНИК')
	date_add = models.DateField(u'Дата добавления', auto_now=True)
	components = models.ManyToManyField(Component)

	class Meta:
		verbose_name_plural='Продукты'
		verbose_name='Продукт'

	def __unicode__(self):
	    return u'%s' % (self.product_title)

class ProductOrdered(models.Model):
	product = models.ForeignKey(Product)
	count = models.IntegerField(max_length=8)
	price = models.DecimalField(max_digits=8, decimal_places=2, default=0)

	class Meta:
		verbose_name_plural='Заказанные продукты'
		verbose_name='Заказанный продукт'

	def get_product(self):
	 	return self.product.product_title+" x"+str(self.count)

	def __unicode__(self):
	    return u'%s x%s' % (self.product.product_title,str(self.count))

class Order(models.Model):
	products = models.ManyToManyField(ProductOrdered)
	order_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
	order_worker = models.IntegerField(max_length=8)
	date_add = models.DateField(u'Дата выполнения', auto_now=True)

	class Meta:
		verbose_name_plural='Заказы'
		verbose_name='Заказ'

	def get_products(self):
		return " | ".join([p.product.product_title+" x"+str(p.count) for p in self.products.all()])

class Stock(models.Model):
	stock_title = models.CharField(u'Наименование', max_length=50, default="")
	stock_discount = models.IntegerField(max_length=3, default=0)
	# stock_is_eternal = models.BooleanField(default=False)
	stock_date_start = models.DateField(u'Дата начала действия акции', default=datetime.date.today)
	stock_date_finish = models.DateField(u'Дата окончания действия акции', default=datetime.date.today)

	products = models.ManyToManyField(Product)
	date_add = models.DateField(u'Дата добавления', auto_now=True, default=datetime.date.today)
	class Meta:
		verbose_name_plural='Акции'
		verbose_name='Акция'
		
	def __unicode__(self):
	    return u'%s' % (self.stock_title)

class Report(models.Model):
	REPORT_CHOICES = (
		(u'Заказ',u'Заказ'),
		(u'Закупка',u'Закупка'),
		(u'Пользователь',u'Пользователь'),
		(u'Компонент',u'Компонент'),
		(u'Продукт',u'Продукт'),
		(u'Акция',u'Акция'),
	)
	report_category = models.CharField(max_length=20, choices=REPORT_CHOICES, default='Заказ')
	report_title = models.CharField(u'Детали', max_length=50)
	report_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
	report_content = models.IntegerField(max_length=8, default=0)
	report_user = models.ForeignKey(User, blank=True, null=True)
	date_add = models.DateField(u'Дата выполнения', auto_now=True)

	class Meta:
		verbose_name_plural='Отчёты'
		verbose_name='Отчёт'

	def __unicode__(self):
	    return u'%s' % (self.report_title)

# мрак
class DayShift(models.Model):
	dayshift_day = models.DateField(u'День', max_length=20, unique=True)
	dayshift_one = models.ForeignKey(User, related_name='dayshift_one', blank=True, null=True)
	dayshift_two = models.ForeignKey(User, related_name='dayshift_two', blank=True, null=True)
	dayshift_three = models.ForeignKey(User, related_name='dayshift_three', blank=True, null=True)
	dayshift_four = models.ForeignKey(User, related_name='dayshift_four', blank=True, null=True)
	dayshift_five = models.ForeignKey(User, related_name='dayshift_five', blank=True, null=True)
	dayshift_six = models.ForeignKey(User, related_name='dayshift_six', blank=True, null=True)

	class Meta:
		verbose_name_plural='Рабочие смены'
		verbose_name='Рабочая смена'
		
	def __unicode__(self):
	    return u'%s' % (self.dayshift_day)

project/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django.db import models
from project.models import Component, Product, Stock, DayShift

class ComponentForm(ModelForm):
	class Meta:
		model = Component
		fields = ['component_title', 'component_count', 'component_price', 'component_type']

class ProductForm(ModelForm):
	class Meta:
		model = Product
		fields = ['product_title', 'product_price', 'product_type', 'components']

class StockForm(ModelForm):
	class Meta:
		model = Stock
		fields = ['stock_title', 'stock_discount', 'stock_date_start', 'stock_date_finish', 'products']


class DayShiftForm(ModelForm):
	class Meta:
		model = DayShift
		fields = ['dayshift_one','dayshift_two','dayshift_three','dayshift_four','dayshift_five','dayshift_six']		



# class OrderForm(ModelForm):
# 	class Meta:
# 		model = Order
# 		fields = ['products','order_price', 'order_worker']

project/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, RequestContext
from django.contrib.auth.decorators import login_required

from accounts.models import User
from project.models import Component, Product, ProductOrdered, Order, Stock, Report, DayShift
from project.forms import ComponentForm , ProductForm, StockForm, DayShiftForm

from datetime import datetime

# Create your views here.


@login_required
def list(request):
	component_list = Component.objects.order_by('component_title');
	product_list = Product.objects.order_by('product_title');
	context = ({
		'page': 'listPage',
		'component_list': component_list,
		'product_list': product_list,
		})
	return render(request, 'project/list.html', context)

@login_required
def component_edit(request, pk):
	component = get_object_or_404(Component, pk=pk)
	if request.method == "POST":
		form = ComponentForm(request.POST, instance=component)
		if form.is_valid():
			component = form.save(commit=False)
			component.save()
			return redirect('list')
	else:
		form = ComponentForm(instance=component)
	return render_to_response('project/component.html', {'form': form},  RequestContext(request))

@login_required
def component_add(request):
	if request.method == 'POST':
		form = ComponentForm(request.POST)
		if form.is_valid():
			component = form.save(commit=False)
			component.save()
	form = ComponentForm()
	context = {'form': form}
	return render_to_response('project/component.html', {'form': form},  RequestContext(request))
	# return render(request, 'project/component.html', context)

@login_required
def product_edit(request, pk):
	product = get_object_or_404(Product, pk=pk)
	if request.method == "POST":
		form = ProductForm(request.POST, instance=product)
		if form.is_valid():
			product = form.save(commit=False)
			product.save()
			return redirect('list')
	else:
		form = ProductForm(instance=product)
	return render_to_response('project/component.html', {'form': form},  RequestContext(request))

@login_required
def product_add(request):
	if request.method == 'POST':
		form = ProductForm(request.POST)
		if form.is_valid():
			product = form.save(commit=False)
			product.save()
	form = ProductForm()
	context = {'form': form}
	return render_to_response('project/component.html', {'form': form},  RequestContext(request))
	# return render(request, 'project/component.html', context)

@login_required
def cashbox(request):
	# if request.method == 'POST':
	# 	print('here')
	# 	request.session['_old_post'] = request.POST.getlist('data')
	# 	return redirect('order')
	product_list = Product.objects.order_by('product_title');
	context = ({
		'page': 'cashPage',
		'product_list': product_list,
		})
	return render(request, 'project/index.html', context)

@login_required
def make_order_ajax(request):
	#if request.POST:
	if request.is_ajax():
		good_list = request.POST.getlist('goods[]')
		count_list = request.POST.getlist('count[]')

		# список действующих акций
		today = datetime.now().date()
		stocks = []
		for stock in Stock.objects.all():
			if stock.stock_date_start <= today:
				if stock.stock_date_finish >= today:
					stocks.append(stock)

		# выполнение заказа
		if good_list:
			order = Order(order_worker=request.session.get('_auth_user_id'))
			order.save()
			for good in good_list:
				product = Product.objects.get(id=good)
				count = count_list[good_list.index(good)] # количество товаров
				price = product.product_price*int(count)
				product_ordered = ProductOrdered(product=product,count=count, price=price)
				product_ordered.save()
				order.products.add(product_ordered)
			order.save()
			
			#тут будут вмешиваться акции

			# for productOrdered in order.products.all():
			# 	for stock in stocks:
			# 		for product in stock.products:
			# 			print(product)
			# print(my_stocks)

			# for productOrdered in order.products.all():
			# 	print(productOrdered.product.productOrdered_title)
			# 	for stock in stocks:
			# 		if productOrdered.product in stock.products:
			# 			print ("YES", productOrdered.product, stock.stock_title)
			
			# assert False
			# for productOrdered in order.products.all():



			# перерасчёт стоимости
			final_price = 0
			for productOrdered in order.products.all():
				final_price = final_price + productOrdered.price
			order.order_price = final_price
			order.save()

			# мистер пропер

			# в случае успешного создания заказа - переадресация
			return HttpResponse('/order/'+str(order.id)+'/')
		return HttpResponse('/')
	return HttpResponseRedirect("/")

@login_required
def order_details(request, pk):
	order = get_object_or_404(Order, pk=pk)
	worker = get_object_or_404(User, pk=order.order_worker)
	print("SSS")
	product_list = []
	for productOrdered in order.products.all():
		product = productOrdered.product
		product_list_item = ({
			'title': product.product_title,
			'count': productOrdered.count,
			'price': product.product_price,
			'final_price': product.product_price * productOrdered.count
			})
		product_list.append(product_list_item)

	context = ({'product_list': product_list,
		'price': order.order_price,
		'worker': worker
	})
	return render(request, 'project/order.html', context)
	#return render_to_response('project/order.html', {'data':context},  RequestContext(request))

@login_required
def stock_list(request):
	stock_list = Stock.objects.order_by('stock_title');
	context = ({
		'stock_list': stock_list,
		'page': 'stockPage',
		})
	return render(request, 'project/stock_list.html', context)

@login_required
def stock_add(request):
	if request.method == 'POST':
		form = StockForm(request.POST)
		if form.is_valid():
			stock = form.save(commit=False)
			stock.save()
	form = StockForm()
	context = {'form': form}
	return render_to_response('project/component.html', {'form': form},  RequestContext(request))


@login_required
def stock_edit(request, pk):
	stock = get_object_or_404(Stock, pk=pk)
	if request.method == "POST":
		form = StockForm(request.POST, instance=stock)
		if form.is_valid():
			stock = form.save(commit=False)
			stock.save()
			return redirect('stock_list')
	else:
		form = StockForm(instance=stock)
	return render_to_response('project/component.html', {'form': form},  RequestContext(request))

@login_required
def employee_list(request):
	today = datetime.now().date()
	dayshift, created = DayShift.objects.get_or_create(dayshift_day=today)
	
	if request.method == "POST":
		form = DayShiftForm(request.POST, instance=dayshift)
		if form.is_valid():
			dayshift = form.save(commit=False)
			dayshift.save()
			return redirect('employee_list')
	form = DayShiftForm(instance=dayshift)	
	context = ({
		'page': 'employeePage',
		'dayShift': dayshift,
		'form': form,
		})
	# return render(request, 'project/employee_list.html', context)
	return render_to_response('project/employee_list.html', context,  RequestContext(request))

@login_required
def employee_list_specific(request, year, month, day):
	today = datetime(int(year), int(month), int(day))
	dayshift, created = DayShift.objects.get_or_create(dayshift_day=today)
	if request.method == "POST":
		form = DayShiftForm(request.POST, instance=dayshift)
		if form.is_valid():
			dayshift = form.save(commit=False)
			dayshift.save()
			return redirect('employee_list_specific', year, month, day)
	form = DayShiftForm(instance=dayshift)	
	context = ({
		'page': 'employeePage',
		'dayShift': dayshift,
		'form': form,
		})
	return render_to_response('project/employee_list.html', context,  RequestContext(request))

	# product = get_object_or_404(Product, pk=pk)
	# if request.method == "POST":
	# 	form = ProductForm(request.POST, instance=product)
	# 	if form.is_valid():
	# 		product = form.save(commit=False)
	# 		product.save()
	# 		return redirect('list')
	# else:
	# 	form = ProductForm(instance=product)
	# return render_to_response('project/component.html', {'form': form},  RequestContext(request))

@login_required
def reports(request):
	report_list = Report.objects.order_by('date_add');
	context = ({
		'page': 'reportPage',
		'report_list': report_list,
		})
	return render(request, 'project/report.html', context)


# some information

def about(request):
	return render(request, 'project/about.html')

templates/project/about.html
{% extends 'base.html' %}
{% block title %} About CoffeEddie {% endblock %}

{% block content %}
	<h1>Welcome to CoffeEddie <small>project</small></h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi corporis vero ea alias perspiciatis, hic reiciendis necessitatibus maxime ipsam, neque deleniti! Possimus, minus nihil odio sit consectetur, odit dicta corporis porro culpa quam hic nostrum deleniti. Iste itaque, maxime repudiandae natus asperiores porro sequi voluptas quas quaerat fuga expedita ducimus quibusdam, eos nisi. Quo dicta debitis officia ea, id rem veritatis cumque, vero alias eveniet repudiandae nam ducimus. Amet possimus iure rerum ducimus quaerat necessitatibus error molestiae! Possimus vel quis sint eaque ipsam, nihil. Maiores alias quia possimus doloribus, at magnam laborum velit odio et voluptatem, sed debitis. Libero, amet.</p>
	<p class="lead">It's the first project</p>
	<h1 class="text-hide">Custom heading</h1>
	<blockquote class="blockquote-reverse">
		<p>It works</p>
		<footer>Sybe at <cite title="The least map">Rust</cite></footer>
	</blockquote>
	<p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident quisquam sunt exercitationem dolore, velit minus doloribus aspernatur modi. Excepturi odit maxime, totam placeat, delectus, nam numquam, sunt repellat facere voluptatum aperiam cupiditate accusantium labore cum possimus. Eaque, laboriosam libero.</p>
	<p>To find out the secret, press <kbd><kbd>ctrl</kbd> + <kbd>M</kbd></kbd></p>
	<p class="text-right">Developer: Alex aka <del>mammontyara</del> <abbr title="true story"><mark>nrkmn</mark></p></abbr>
	<p class="bg-success">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum vel veniam voluptatum quidem voluptates laudantium inventore quae dicta vitae officiis.</p>
	<p class="text-center">Updates:</p>
	<p>
		<dl class="dl-horizontal">
			<dt>First</dt>
			<dd>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem corporis veniam, dolore commodi, doloremque, beatae quas placeat tempore voluptatibus at nesciunt corrupti ad nobis quibusdam vero ratione. Maiores voluptates et blanditiis reprehenderit quae necessitatibus autem repellendus illo! Consequuntur, quisquam, nostrum.</dd>
			<dt>Second</dt>
			<dd>There was a move of Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, quod!</dd>
			<dt>And the lasts</dt>
			<dd>There was a Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem et sunt adipisci, cumque dolor, dignissimos eaque alias. Dolore vitae, animi.</dd>
		</dl>
	</p>
{% endblock content %}

templates/project/component.html
{% extends 'base.html' %}

{% block title %}Добавление компонента{% endblock %}

{% block content %}

<form method="POST" class="post-form">{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="save btn btn-default">Save</button>
</form>

<!-- <hr>
<p class="lead">Here lies test form <small>for self-development</small></p>

<blockquote>
	For keeping time I'm gonna make form for user personal profile
</blockquote>

<h2 class="text-center">My Profile</h2>

<form class="form-horizontal" role="form">
	<div class="form-group">
		<label for="inputFirstName" class="col-sm-2 control-label">Имя</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="inputFirstName" placeholder="Вениамин">
		</div>
	</div>
	<div class="form-group">
		<label for="inputLastName" class="col-sm-2 control-label">Фамилия</label>
		<div class="col-sm-10">
			<input type="text" class="form-control" id="inputFirstName" placeholder="Перепёлкин">
		</div>
	</div>
	<div class="form-group">
		<label for="inputFile" class="col-sm-2 control-label">Выберите изображение</label>
		<div class="col-sm-10">
			<input type="file" class="btn btn-default" id="inputFile">
			<p class="help-block">В формате Jpg, не больше 1 мб</p>
		</div>
	</div>
	<div class="form-group">
		<label for="inputFile" class="col-sm-2 control-label">Выберите цвет профиля</label>
		<div class="col-sm-10">
			<input type="color">
			<p class="help-block">В формате Jpg, не больше 1 мб</p>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<div class="checkbox">
				<label><input type="checkbox">
					Подтверждаю согласие с <a href="/about/">условиями</a> компании CoffeEddie
				</label>
				
			</div>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Сохранить изменения</button>
		</div>
	</div>
</form> -->


{% endblock %}

templates/project/employee_list.html
{% extends 'base.html' %}

{% block title %}Акции{% endblock %}

{% block content %}

	 <script>
		$(function() {
			$( "#datepicker" ).datepicker({
				onSelect: function(dateText, inst) {
					console.log(inst);
					window.location = '/employees/'+inst.selectedYear+
						'/'+(parseInt(inst.selectedMonth)+1)+'/'+inst.selectedDay;
				}
			})
		});
	</script>
	
	<div class="row">
		<div class="col-sm-5">
			<p>Date: <input type="text" id="datepicker"></p>
		</div>
		<div class="col-sm-7">
			<form method="POST" class="post-form">{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="save btn btn-default">Save</button>
			</form>
		</div>
	</div>




{% endblock %}

templates/project/index.html
{% extends 'base.html' %}

{% block title %} Касса {% endblock %}

{% block content %}
	<div class="row">
		<div class="col-sm-7 leftCash">
			<!-- table.table>thead>td{some}*5>^tr*30>td{good $}*5 -->

				<input type="text" class="form-control" placeholder="Введите название товара" ng-model="good_query">
				<hr>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>Название</th>
							<th>Категория</th>
							<th>Цена</th>
						</tr>
					</thead>
					<tbody>
						{% for product in product_list %}
						<tr class="cash_prod_elem" id="{{product.id}}">
							<td>{{product.product_title}}</td>
							<td>{{product.get_product_type_display}}</td>
							<td>{{product.product_price}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

		</div>
		<div class="col-sm-5 rightCash">

			<div class="text-center">
				<form id="order" method="post">{% csrf_token %}
					<button type="submit" class="btn btn-default btn-lg">Checkout</button>
				</form>
			</div>
	
			<!--<div id="checkout" class="btn btn-default col-sm-offset-3 col-sm-6">Checkout</div>-->
			<hr/>
			<!-- <div class="btn btn-default col-sm-4">Remove</div>
			<div class="btn btn-default col-sm-4">Change</div>
			<div class="btn btn-default col-sm-4">Some</div> -->

			<table id="table_checkout" class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Название</th>
						<th>Кол-во</th>
						<th>Цена</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>

		</div>
	</div>
{% endblock %}

templates/project/list.html
{% extends 'base.html' %}

{% block title %}Товары{% endblock %}

{% block content %}

	<div class="row">
		<div class="col-sm-6">
			<h2>Компоненты</h2>
			<a href="/component/add/" class="btn btn-default col-sm-4">Add</a>
			<div id="btn_comp_change" class="btn comp_btn btn-default disabled col-sm-4" data-toggle="modal" data-target="#myModal">Change</div>
			<div id="btn_comp_remove" class="btn comp_btn btn-default disabled col-sm-4">Remove</div>
			<div class="clearfix"></div>
			<hr>
			<input type="text" class="form-control" placeholder="Text here good title for filtering">
			{% if component_list %}
				<table class="table table-striped table-hover table-condensed">
					<thead>
						<tr>
							<th>Наименование</th>
							<th>Категория</th>
							<th>Кол-во</th>
							<th>Цена</th>
						</tr>
					</thead>
					<tbody>
						{% for component in component_list %}
						<tr class="comp_elem" id="{{component.id}}">
							<td>{{component.component_title}}</td>
							<td>{{component.get_component_type_display}}</td>
							<td>{{component.component_count}}</td>
							<td>{{component.component_price}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			{% else %}
			<p>No products are available.</p>
			{% endif %}
		</div>
		<div class="col-sm-6">
			<h2>Товары</h2>
			<a href="/product/add/" class="btn btn-default col-sm-4">Add</a>
			<div  id="btn_prod_change" class="btn prod_btn btn-default disabled col-sm-4" data-toggle="modal" data-target="#myModal">Change</div>
			<div  id="btn_prod_remove" class="btn prod_btn btn-default disabled col-sm-4">Remove</div>
			<div class="clearfix"></div>
			<hr>
			<input type="text" class="form-control" placeholder="Text here good title for filtering">
			{% if product_list %}
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th>Наименование</th>
								<th>Категория</th>
								<th>Цена</th>
							</tr>
						</thead>
						<tbody>
							{% for product in product_list %}

							<tr class="prod_elem" id="{{product.id}}">
								<td>{{product.product_title}}</td>
								<td>{{product.get_product_type_display}}</td>
								<td>{{product.product_price}}</td>
							</tr>
							{% endfor %}
						</tbody>

					</table>
				{% else %}
				<p>No products are available.</p>
			{% endif %}
		</div>
	</div>

{% endblock %}

templates/project/order.html
{% extends 'base.html' %}

{% block title %}Заказ{% endblock %}

{% block content %}

<h3>Заказ подробно</h3>

{% for product in product_list %}

	<p>{{product.title}} - {{product.count}} шт | {{product.final_price}} руб</p>

{% endfor %}

<h3>Применённые акции</h3>
	Воу, воу, палехчи, парниша
<h3>Итоговая стоимость</h3>
<p>{{price}} руб</p>
<p>Работник: {{worker.get_full_name}}</p>
<div class="btn btn-default">Печать</div>
<a href="/" class="btn btn-default">Завершение</a>
{% endblock %}